# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "http://zaggonaut.dev"

[_.globalMeta]
title = "Veegish Ramdani"
description = "My personal space"
longDescription = "Everything here is about me, my thoughts, my projects, and my journey."
cardImage = "https://avatars.githubusercontent.com/u/8150534"
keywords = ["web development", "design", "technology"]

[_.blogMeta]
title = "Veegish Blog"
description = "Practical wisdom, unfiltered thoughts, and hot takes."
longDescription = "Web development, tech trends, and the occasional programming mishap."
cardImage = "https://avatars.githubusercontent.com/u/8150534"
keywords = ["web development", "design", "technology"]

[_.projectMeta]
title = "Veegish Projects"
description = "A list of my web development projects and developer tools."
longDescription = "All of my projects, including both frontend and full-stack applications."
cardImage = "https://avatars.githubusercontent.com/u/8150534"
keywords = ["web development", "design", "technology"]

[_.notFoundMeta]
title = "Veegish 404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "https://avatars.githubusercontent.com/u/8150534"

[_.hero]
title = "Veegish"
subtitle = "A personal space for my thoughts, projects, and journey"
extraText= "As a software engineer, a big part of my job is fixing bugs, solving performance issues and making sure that the code is clean and maintainable. This site is the opposite of that. Enjoy the bugs, the added performance overheads and the lack of concern for high standards. I'm not sorry."
image = "https://avatars.githubusercontent.com/u/8150534"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "Veegish Ramdani"
githubProfile = "https://github.com/VEEGISHx"
twitterProfile = "https://twitter.com/veegish24"
linkedinProfile = "https://mu.linkedin.com/in/veegish"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/articles"
guestbook = "/guestbook"
about = "#disabled"
